services:
  postgres:
    image: postgres:16-alpine
    container_name: playerload-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: playerload
      POSTGRES_USER: playerload
      POSTGRES_PASSWORD: secret
    volumes:
      - playerload_pg_data:/var/lib/postgresql/data

volumes:
  playerload_pg_data:
